services:
  orthus-relay:
    privileged: true
    network_mode: "host"
    restart: always
    image: jackmead515/orthus-relay:0.0.4-arch
    ports:
      - "5454:5454"
    environment:
      - NODE_ENV=prod
      - STREAM_HOST=0.0.0.0
      - HTTP_HOST=0.0.0.0

  orthus-app:
    privileged: true
    network_mode: "host"
    restart: always
    volumes:
      - /dev/:/dev/
      - /tmp/:/data/
    image: jackmead515/orthus-app:0.0.4-arch
    ports:
      - "8000:8000"
    environment:
      - STREAM_NAME=webcam
      - STREAM_HOST=0.0.0.0
      - STREAM_PORT=3131
      - STREAM_CONFIG="ffmpeg -an -f v4l2 -i /dev/video0 -video_size 2560x720 -framerate 30 -threads 4 -f tee -map 0:v -f segment -vcodec mjpeg -qscale:v 3 -segment_time 10 -reset_timestamps 1 -strftime 1 %s.mp4 -map 0:v -f mpegts -vcodec mpeg1video -qscale:v 18 -vf \"crop=(iw/2):ih:0:0\" udp://0.0.0.0:3131"
      - RECORD_DIRECTORY=/data
      - DEBUG=true