version: '3.8'

services:
  orthus-relay:
    privileged: true
    network_mode: "host"
    image: jackmead515/orthus-relay:0.0.2-arch
    ports:
      - "5454:5454"
    environment:
      - NODE_ENV=prod
      - STREAM_HOST=0.0.0.0
      - HTTP_HOST=0.0.0.0

  orthus-app:
    privileged: true
    network_mode: "host"
    volumes:
      - /dev/:/dev/
      - /data/:/tmp/
    image: jackmead515/orthus-app:0.0.2-arch
    ports:
      - "8000:8000"
    environment:
      - STREAM_NAME=webcam
      - STREAM_HOST=0.0.0.0
      - STREAM_PORT=3131
      - INFPS=30
      - INRES=2560x720
      - OUTRES=2560x720
      - OUTFPS=30
      - BITRATE=1024k
      - THREADS=0
      - VSYNC=2
      - SEGMENT_TIME=10
      - VIDEO_INDEX=0
      - ARCHIVE=1
      - GRAYSCALE=0
      - RECORD_DIRECTORY=/data
      - DEBUG=true